### PR TITLE
iOS版切换为iOS定位SDK V1.4版, 解决xcode10无法构建的问题

### PR DESCRIPTION
**Pull request by lazydan**
iOS版切换为iOS定位SDK V1.4版, 解决xcode10无法构建的问题, 但之后不支持返回title和subtitle

### CODE REVIEW

**Comment by aruis** [comment]
好像删除了不少.h 文件，没啥问题吧？

**Comment by lazydan** [comment]
因为换了百度ios的库版本 , 旧版为了反解析地址添加了好几个库,  新版定位的库就带反解析功能, 所以把旧库都删了

**Comment by aruis** [comment]
@lazydan 感谢，已合并。 ❤️

**Comment by jingyinzhou** [comment]
ionic cordova plugin add https://github.com/aruis/cordova-plugin-baidumaplocation.git 
这样 安装不了插件呢。
报错信息：
(node:1736) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin https://github.com/aruis/cordova-plugin-baidumaplocation.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --mirror -q https://github.com/aruis/cordova-plugin-baidumaplocation.git /Users/gan/.npm/_cacache/tmp/git-clone-f130b7ae/.git
npm ERR! warning: templates not found in /var/folders/ln/kwsrk1k17t76pkth7bz5c6ym0000gn/T/pacote-git-template-tmp/git-clone-d2f398d7
npm ERR! error: RPC failed; curl 18 transfer closed with outstanding read data remaining
npm ERR! fatal: the remote end hung up unexpectedly
npm ERR! fatal: early EOF
npm ERR! fatal: index-pack failed
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gan/.npm/_logs/2019-07-13T02_44_53_758Z-debug.log
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:37
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:1736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
环境：
Ionic:

   Ionic CLI          : 5.2.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 10 other plugins)

Utility:

   cordova-res : 0.5.1 (update available: 0.6.0)
   native-run  : not installed

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.11.1 (/usr/local/bin/node)
   npm        : 6.4.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001

**Comment by lazydan** [comment]
@jingyinzhou  看着像是网络原因  无法下载到插件

**Pull request merged**
